--DROP TABLE add_coastline_medium_res_line_ CASCADE CONSTRAINTS;
--DELETE FROM mdsys.user_sdo_geom_metadata WHERE table_name = 'ADD_COASTLINE_MEDIUM_RES_LINE_' AND column_name = 'GEOM';

select * from add_coastline_medium_res_line_;

----------------------------------------------------
-- 6. тип пространственных данных
----------------------------------------------------
SELECT column_name, data_type 
FROM user_tab_columns 
WHERE table_name = 'ADD_COASTLINE_MEDIUM_RES_LINE_' 
AND column_name = 'GEOM';

----------------------------------------------------
-- 7. SRID
----------------------------------------------------
SELECT srid 
FROM USER_SDO_GEOM_METADATA 
WHERE table_name = 'ADD_COASTLINE_MEDIUM_RES_LINE_';


--Идентификатор пространственной привязки (SRID) - это уникальный идентификатор, 
--соответствующий определенной системе координат, допуску и разрешению1. 
--SRID используется для определения местоположения объекта в пространстве 
--и преобразования координат 
--между различными системами и единицами измерения.


----------------------------------------------------
-- 8. Определите атрибутивные столбцы.
----------------------------------------------------
SELECT column_name, data_type 
FROM user_tab_columns 
WHERE table_name = 'ADD_COASTLINE_MEDIUM_RES_LINE_';


----------------------------------------------------
-- 9. описание пространственных объектов в формате WKT
----------------------------------------------------
SELECT SDO_UTIL.TO_WKTGEOMETRY(GEOM) 
FROM ADD_COASTLINE_MEDIUM_RES_LINE_;

--WKT (Well-Known Text) - это текстовый формат для представления геометрических объектов
----------------------------------------------------
-- 10. 
----------------------------------------------------
--10.1. пересечение пространственных объектов
SELECT 
    SDO_UTIL.TO_WKTGEOMETRY(SDO_GEOM.SDO_INTERSECTION(a.geom, b.geom, 0.005)) as intersection
FROM 
    ADD_COASTLINE_MEDIUM_RES_LINE_ a, 
    ADD_COASTLINE_MEDIUM_RES_LINE_ b
WHERE 
    SDO_ANYINTERACT(a.geom, b.geom) = 'TRUE';
--10.2
--SELECT SDO_UTIL.TO_WKTGEOMETRY(SDO_AGGR_UNION(SDOAGGRTYPE(geom, 0.005))) as union_geom
--FROM ADD_COASTLINE_MEDIUM_RES_LINE_;
--10.3
--SELECT a.geom, b.geom
--FROM ADD_COASTLINE_MEDIUM_RES_LINE_ a, ADD_COASTLINE_MEDIUM_RES_LINE_ b
--WHERE SDO_GEOM.RELATE(a.geom, 'anyinteract', b.geom, 0.005) = 'TRUE';
--10.4
--SELECT SDO_UTIL.TO_WKTGEOMETRY(SDO_UTIL.SIMPLIFY(GEOM, 0.005)) AS SIMPLIFIED_GEOM 
--FROM ADD_COASTLINE_MEDIUM_RES_LINE_;

--10.2 координаты вершин пространственного объектов
SELECT a.x, a.y
FROM ADD_COASTLINE_MEDIUM_RES_LINE_ t 
CROSS JOIN TABLE (SDO_UTIL.GETVERTICES (t.geom)) a;


--10.3
-- Для расчета площади пространственных объектов
SELECT SDO_GEOM.SDO_AREA(geom, 0.005) AS area
FROM my_geometry;

----------------------------------------------------
-- 11. Создайте пространственный объект в виде точки (1) /линии (2) /полигона (3).
----------------------------------------------------
--DROP TABLE my_geometry;

CREATE TABLE my_geometry (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  geom SDO_GEOMETRY,
  PRIMARY KEY (id)
);
-- точка
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2001,  -- gtype (2D point)
    3031,  -- SRID
    SDO_POINT_TYPE(1, 1, NULL),  -- point (X, Y, Z)
    NULL,  -- element info
    NULL   -- ordinates
  )
);
-- линия
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2002,  -- gtype (2D line)
    3031,  -- SRID
    NULL,  -- point
    SDO_ELEM_INFO_ARRAY(1, 2, 1),  -- element info (starting offset, ETYPE, interpretation)
    SDO_ORDINATE_ARRAY(1, 1, 2, 2)  -- ordinates (X, Y pairs)
  )
);
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2002,  -- gtype (2D line)
    3031,  -- SRID
    NULL,  -- point
    SDO_ELEM_INFO_ARRAY(1, 2, 1),  -- element info (starting offset, ETYPE, interpretation)
    SDO_ORDINATE_ARRAY(3, 3, 4, 4)  -- ordinates (X, Y pairs)
  )
);
-- полигон
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2003,  -- gtype (2D polygon)
    3031,  -- SRID
    NULL,  -- point
    SDO_ELEM_INFO_ARRAY(1, 1003, 1),  -- element info (starting offset, ETYPE, interpretation)
    SDO_ORDINATE_ARRAY(1, 1, 2, 2, 3, 3, 1, 1)  -- ordinates (X, Y pairs)
  )
);
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2003,  -- gtype (2D polygon)
    3031,  -- SRID
    NULL,  -- point
    SDO_ELEM_INFO_ARRAY(1, 1003, 1),  -- element info (starting offset, ETYPE, interpretation)
    SDO_ORDINATE_ARRAY(1, 1, 2, 2, 2, 1, 1, 1)  -- ordinates (X, Y pairs)
  )
);
INSERT INTO my_geometry (geom)
VALUES (
  SDO_GEOMETRY(
    2003,  -- gtype (2D polygon)
    3031,  -- SRID
    NULL,  -- point
    SDO_ELEM_INFO_ARRAY(1, 1003, 1),  -- element info (starting offset, ETYPE, interpretation)
    SDO_ORDINATE_ARRAY(1, 1, 3.034, 3.034, 3.034, 1, 1, 1)  -- ordinates (X, Y pairs)
  )
);


select SDO_UTIL.TO_WKTGEOMETRY(geom) from my_geometry;


----------------------------------------------------
-- 12. Найдите, в какие пространственные объекты попадают созданные вами объекты.
----------------------------------------------------
SELECT SDO_UTIL.TO_WKTGEOMETRY(a.geom), SDO_UTIL.TO_WKTGEOMETRY(b.geom)
FROM my_geometry a, my_geometry b
WHERE SDO_GEOM.RELATE(a.geom, 'anyinteract', b.geom, 0.005) = 'TRUE';




--13.
--просмотр индекса
SELECT index_name, table_name
FROM all_indexes
WHERE table_name = 'MY_GEOMETRY' AND index_type = 'DOMAIN';


-- Создание пространственного индекса для колонки с геометрическими объектами
CREATE INDEX idx_my_geometry_geom
ON my_geometry(geom)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;


--14
CREATE OR REPLACE PROCEDURE find_geometry (
  p_x IN NUMBER,
  p_y IN NUMBER,
  p_id OUT NUMBER
) AS
  v_geom SDO_GEOMETRY;
BEGIN
  SELECT geom INTO v_geom
  FROM my_geometry
  WHERE SDO_CONTAINS(geom, SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(p_x, p_y, NULL), NULL, NULL)) = 'TRUE';
  p_id := v_geom.id;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    p_id := NULL;
END find_geometry;

